# Generated by Django 3.1.7 on 2021-04-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20210427_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_description', models.CharField(max_length=250)),
                ('event_location', models.CharField(max_length=250)),
                ('event_date', models.DateTimeField()),
                ('event_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product')),
                ('event_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='persona.eventtype')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
