# Generated by Django 3.1.7 on 2021-04-30 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210501_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 0, 45, 22, 862215)),
        ),
    ]
