# Generated by Django 3.1.7 on 2021-05-01 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20210501_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(default=models.CharField(max_length=250), max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 0, 53, 26, 427137)),
        ),
    ]
