# Generated by Django 3.1.7 on 2021-05-02 01:20

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0005_auto_20210502_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 2, 20, 30, 737454)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(default=django.contrib.auth.models.User, max_length=255),
        ),
    ]
