# Generated by Django 3.1.7 on 2021-05-02 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_auto_20210502_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_creator',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 3, 3, 1, 926433)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(max_length=255),
        ),
    ]
