# Generated by Django 3.1.7 on 2021-05-02 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20210502_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 16, 25, 2, 986197)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
